# This is a basic workflow to help you get started with Vue s3 deployer action

name: Deployment

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploying application to Amazon S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
          source_dir: 'static'