# This is a basic workflow to help you get started with Vue s3 deployer action

name: Deployment

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploying application to Amazon S3
        uses: aws-actions/configure-aws-credentials@v1
        id: S3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-bucket: ${{ secrets.AWS_BUCKET_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}